### PR TITLE
comparison operator

### PR DESCRIPTION
**Pull request by mkosir**
This PR tries to fix opened [issue](https://github.com/ttag-org/ttag/issues/154) where @AlexMost pointed at the source code location :).  
Comparison operators are currently written in JavaScript notation, but `.po` files structure and associated software (e.g. Poedit) uses different ones.
Tests has been modified and successfully passed.

### CODE REVIEW

**Comment by AlexMost** [comment]
Thanks for the PR!

**Comment by AlexMost** [comment]
Ah, I just have tried this new version and seems like you have changed `===` to just `=` but not `==`. Can you please fix that?

**Comment by mkosir** [comment]
Sorry if I missed some of them, but can't see which one do you mean?

**Comment by AlexMost** [comment]
I see that you have changed all `===` to `=` which is not a comparison operator. This line for instance - https://github.com/ttag-org/plural-forms/pull/2/files#diff-98a1cd4cb0257d4fa9ad62cd997700edR99

Plural forms formula must be a valid C expression. Here are some examples in the doc: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

**Comment by mkosir** [comment]
I see, totally missed that one out, created new [PR](https://github.com/ttag-org/plural-forms/pull/3)

**Pull request merged**
